# Generated by Django 3.0.5 on 2020-10-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('buyer', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('photo', models.FileField(upload_to='')),
                ('minimumBid', models.FloatField()),
                ('maximumBid', models.FloatField()),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
