# Generated by Django 3.0.5 on 2020-10-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_auto_20201024_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
