# Generated by Django 3.0.5 on 2020-10-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auto_20201024_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='id',
            new_name='bidId',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='productId',
        ),
    ]
