# Generated by Django 3.0.5 on 2020-10-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_auto_20201024_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='amount',
            field=models.FloatField(default=5000),
            preserve_default=False,
        ),
    ]
