# Generated by Django 3.0.5 on 2020-10-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_bids_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
