# Generated by Django 3.0.5 on 2020-10-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0009_auto_20201025_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='seller',
        ),
    ]
