# Generated by Django 3.0.5 on 2020-10-25 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0010_remove_bids_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credits',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='winningBid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidding.Bids'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='credits',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
